### ISSUE TITLE
AUTHORS

### ISSUE THREAD

**Issue by varlesh** [jcmljunior/Materia-OSX#1]
You use my sources:
https://raw.githubusercontent.com/PapirusDevelopmentTeam/materia-kde/master/aurorae/themes/Materia-Dark/decoration.svg
https://raw.githubusercontent.com/jcmljunior/Materia-OSX/master/Materia-Dark-OSX/decoration.svg

https://raw.githubusercontent.com/PapirusDevelopmentTeam/materia-kde/master/aurorae/themes/Materia-Light/decoration.svg
https://raw.githubusercontent.com/jcmljunior/Materia-OSX/master/Materia-OSX/decoration.svg
Where AUTHORS?
https://github.com/PapirusDevelopmentTeam/materia-kde/blob/master/aurorae/themes/Materia-Light/AUTHORS

**Comment by jcmljunior** [comment]
Hi @varlesh 
Yes, I use parts of your code.
I will add the authors to my project. thank you for the warning.

**Comment by jcmljunior** [comment]
Hi @varlesh 
Could you check if everything is all right now?
Thanks
